#!/usr/bin/env ruby
# frozen_string_literal: true

require 'w3c_validators'
require 'socket'

STRICT_REMOTE_VALIDATION = ENV['STRICT_REMOTE_VALIDATION'] == '1'

def validator(file)
  extension = File.extname(file)
  if extension == '.html'
    W3CValidators::NuValidator.new
  elsif extension == '.css'
    W3CValidators::CSSValidator.new
  end
end

def validate(file)
  puts "Checking #{file}..."

  path = File.expand_path "../_site/#{file}", __dir__
  results = validator(file).validate_file(path)

  return puts 'Valid!' if results.errors.empty?

  results.errors.each { |err| puts err.to_s }
  exit 1
rescue W3CValidators::ValidatorUnavailable, SocketError => e
  if STRICT_REMOTE_VALIDATION
    warn "Remote validator unavailable: #{e.message}"
    exit 1
  end

  warn "Skipping #{file}: remote validator unavailable (set STRICT_REMOTE_VALIDATION=1 to fail CI)"
end

validate 'index.html'
validate File.join 'assets', 'css', 'style.css'
